### ISSUE TITLE
1 to 0 ?

### ISSUE THREAD

**Issue by lpatiny** [mljs/ml-roc-multiclass#1]
I'm always use in a Roc curve to start with the point 0,0

![image](https://user-images.githubusercontent.com/1484241/125057370-701d5f00-e0a9-11eb-854b-fc9cec22a626.png)

But in your case it starts from 0,1

![image](https://user-images.githubusercontent.com/1484241/125057417-7e6b7b00-e0a9-11eb-958b-cef87c765cd3.png)

@josoriom How to you explain this ?

**Comment by josoriom** [comment]
The plot above is TPR vs FPR and the output of the code is sensitivities vs specificities, sensitivity = TPR but specificity = 1-FPR.
